.TH shell "1" "September 2023" "Shell Manual" "User Commands"

.SH NAME
shell \- A custom shell program

.SH SYNOPSIS
.B shell
[\fIOPTION\fR]...

.SH DESCRIPTION
Shell is a custom shell program that allows you to interact with your system. You can use it to run commands, execute scripts, and manage processes.

.SH OPTIONS
The following options are available:

.TP
.B \-\-help
Display help information.

.SH USAGE
To run Shell, simply type "shell" in your terminal.

.SH COMMANDS
Shell supports the following built-in commands:

.TP
.B env
Display the current environment variables.

.TP
.B exit
Exit the shell program.

.SH INTERACTIVE MODE
In interactive mode, Shell reads and executes commands entered by the user. You can run external programs and built-in commands.

.SH SCRIPTING
You can also create shell scripts with Shell by placing a sequence of commands in a text file and running the script using the shell.

.SH EXIT STATUS
Shell returns the exit status of the last executed command as its own exit status.

.SH AUTHOR
Written by Anass El Hamdi Alaoui.

.SH REPORTING BUGS
Report bugs to anassalaoui0593@gmail.com.

.SH COPYRIGHT
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH NOTES
This manual page was created using the "man" command.

.SH BUGS
No known bugs at this time.
